### PR TITLE
When the mvn command fails for example due to lack of space, make sure the whole build fails.

### PR DESCRIPTION
**Pull request by adelton**
Many thanks for submitting your Pull Request :heart:!

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/trustyai-explainability/trustyai-explainability/blob/main/CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `FAI-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.3.x] FAI-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by adelton** [comment]
Seeing this repo is forked from https://github.com/trustyai-explainability/trustyai-explainability, should I rather do the pull request there?

**Comment by RobGeada** [comment]
Hi @adelton, sorry, just noticed this. Yeah, please open the pull request upstream at https://github.com/trustyai-explainability/trustyai-explainability and we'll merge it down

**Comment by adelton** [comment]
Filed https://github.com/trustyai-explainability/trustyai-explainability/pull/421 now.

**Comment by ruivieira** [comment]
Merged upstream with https://github.com/trustyai-explainability/trustyai-explainability/pull/421

**Pull request closed without merging**
